# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentedGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Good')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='start date of the reservation')),
                ('end_date', models.DateTimeField(verbose_name='end date of the reservation')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='StoragedGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='beginning of the storaging')),
                ('end_date', models.DateTimeField(verbose_name='end of the storaging')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Good')),
            ],
        ),
        migrations.AddField(
            model_name='rentedgood',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='things.Reservation'),
        ),
    ]
