# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20171125_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentedgood',
            name='good_id',
        ),
        migrations.RemoveField(
            model_name='rentedgood',
            name='reservation_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='good_id',
            field=models.ForeignKey(default=121, on_delete=django.db.models.deletion.CASCADE, to='things.Good'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RentedGood',
        ),
    ]
