# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_auto_20171125_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='reservation_type',
            field=models.CharField(choices=[('0', 'is_rented'), ('1', 'is_cancelled'), ('2', 'is_declined')], default=0, max_length=1, verbose_name='type'),
            preserve_default=False,
        ),
    ]
