# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_auto_20171125_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='image_path',
            field=models.CharField(default='images/square.png', max_length=200, verbose_name='image'),
            preserve_default=False,
        ),
    ]
