# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_good_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_status',
            field=models.CharField(choices=[('0', 'at_service'), ('1', 'at_home'), ('2', 'damaged'), ('3', 'lost')], default=0, max_length=1, verbose_name='status'),
            preserve_default=False,
        ),
    ]
