# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_good_good_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='good_status',
            new_name='status',
        ),
    ]
