# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20171125_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 25, 22, 29, 32, 173171, tzinfo=utc), verbose_name='date of return'),
            preserve_default=False,
        ),
    ]
